### ISSUE TITLE
Convertir una expresión en bruto a identificador y expression

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#11]
La tarea consiste en extraer de la expresión en bruto "nombreVariable = expresión" en:
"nombreVariable" como un String
"expresion" como un String
Lo que se hará a continuación con estos dos Strings es lo siguiente:

``` java
ExpressionTree.putVar("nombreVariable", new ExpressionInfix("expresion"));
```

Lo que creará un árbol de expresión (en el ejemplo se crea a partir de una expresión infija) para luego meterle en el diccionario de variables que por el momento se aloja de manera estática en la clase ExpressionTree aunque.

**Comment by ismtabo** [comment]
¿Esto es lo que quieres hacer para las asignaciones?

**Comment by garciparedes** [comment]
No, esto es lo que estaba hecho ahora mismo, no es lo que te planteaba por telegram, aunque se puede hacer una adaptación de ambas

**Comment by ismtabo** [comment]
Ya está adaptado, ahora mismo cuando tu haces una asignación como has definido, se filtra mediante el `ExpressionController` que diferencia entre operaciones y asignaciones. En caso de ser una asignación se guarda en mapa de `ExpressionTree` y se guarda en una variable la parte de la derecha en una variable del controlador llamada `expressionTree`. 

Si fuese una operación se crea un `ExpressionTree` y se guarda en la variable `expressionTree`.

De esta manera cuando el Controlador del programa quiera conocer el resultado, el controlador de expresiones evalua `expressionTree`, es decir la operación actual que había que evaluar.
