### ISSUE TITLE
Los ExpressionTree deberían lanzar excepciones en caso de que ocurra un error al operar.

### ISSUE THREAD

**Issue by ismtabo** [ismtabo/cc_bigintegers#15]

**Comment by garciparedes** [comment]
Puse algunas excepciones pero se me debieron colar la mayoría. Si puedes decir los casos en que faltan ayudaría a localizarlas y solucionarlas con mayor facilidad.

**Comment by ismtabo** [comment]
Pues voy a intentar encargarme primero de la interfaz y luego te comento los fallos que haría falta coger.
