### ISSUE TITLE
"Pulir" interfaz gráfica

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#2]

**Comment by ismtabo** [comment]
Podemos hacer un diseño de como queremos que quede la interfaz gráfica. Voy a utilizar una aplicación llamada [Pencil](http://pencil.evolus.vn/Downloads.html) para hacerlo y lo meteré en una carpeta aparte dentro del repositorio, en la carpeta de `doc`, llamada `design`.

He añadido un primer diseño, a ver que te parece

**Comment by garciparedes** [comment]
Me parece buena idea, si que estaría bien plantearlo primeramente como un boceto. Si te parece bien quieres ser tú el encargado de hacer un primer boceto y que trabajemos a partir de él?

**Comment by ismtabo** [comment]
Ya está creado un pequeño boceto, que se parece algo a derive. Imagino que se puede iniciar a partir de ahí.

**Comment by garciparedes** [comment]
Se me ha ocurrido que podríamos poner  RadioButtons (aporte de Silvia) para pasar de base Decimal a Hexadecimal ya que el profesor nos dijo que la salida debía ser en hexadecimal.
