### ISSUE TITLE
Analizar el trabajo realizado hasta el momento y proponer cambios de enfoque si fuera necesario.

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#3]

**Comment by ismtabo** [comment]
¿Lo que tenemos es una calculadora por el momento con botones auxiliares en la parte inferior para las operaciones?

**Comment by garciparedes** [comment]
Si, estuve trabajando en hacer las operaciones, pero como el otro día hablamos, es mejor hacerlo tipo derive que calcule todo de una vez, así que eso lo cambie.
En los commits anteriores está cómo lo hice, pero no creo que nos sirva para el nuevo enfoque.
Así que por mi parte creo que los botones solo deberían añadir los símbolos en la línea de comandos.

Quizás estaría bien también que tuviese el teclado numérico, pero ese es un tema que deberíamos debatir en la tarea #2
