### ISSUE TITLE
Encontrado bug de sintaxis al asignar variables

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#30]
Ahora mismo solo deja asignar variables con el siguiente formato:
`variable = expresión` fijando estrictamente el número de espacios.
Propongo que se eliminen todos los espacios con 

```
string.replaceAll("\\s+", "")
```

y a partir de ahí se busque "=" en vez de " = "

**Comment by ismtabo** [comment]
@garciparedes Me parece bastante bien, revisa las expresiones regulares de Operation para las operaciones complejas, que creo que tenían en cuenta los espacios.
