### ISSUE TITLE
Implementar persistencia de valores en variables para su uso en posteriores operaciones

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#4]

**Comment by ismtabo** [comment]
Había  pensado que se podría utilizar un mapa para la persistencia. Ya que se aceptan valores únicos y están asignados a un nombre en concreto.

**Comment by garciparedes** [comment]
Si, yo también lo he estado pensando y creo que el mapa es la opción que cumple todos los requisitos que necesitamos. Ya que además tiene la cualidad de que se sobreescribe el valor anterior al introducir otro nativamente, con lo que eso que nos ahorramos jeje
