### ISSUE TITLE
¿Qué hacer cuando se introduce en expresión variables no asignadas?

### ISSUE THREAD

**Issue by garciparedes** [ismtabo/cc_bigintegers#6]
Creo que deberíamos dejar claro qué va a suceder en este caso.

Se me ocurren varias alternativas posibles:
- Utilizar esa variable como si su valor fuese 0.
- Dar un mensaje de error en el momento de la introducción.
- Permitir introducir la expresión y comprobar si está definida o no en el momento en que se pida el resultado de la variable por si las variable se ha instanciado posteriormente, es decir, evaluación perezosa.

**Comment by ismtabo** [comment]
Opto por la opción 3 aunque añadiría lo de buscar esa variable dentro de un mapa de variables, y si no encuentra una coincidencia daría un error, no se ejecuta la expresión y se muestra en pantalla el nombre de la variable no definida.
